services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    depends_on:
      - face-detection
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
  face-detection:
    build: ./face-detection
    ports:
      - "8000:8000"
    volumes:
      - ./face-detection:/app 